---
title: "Week 5 In-class Assignment"
author: "Felix Ho"
date: "2024-10-07"
format: docx
---

```{r}
#| label: load-packages
#| include: false
library(here)
library(table1)
# library(kableExtra) #Gets nicer `table1` LaTeX output for pdf.
library(flextable) #Gets nicer `table1` .docx output. 
library(tidyverse)
```

Create Table 1 for armed conflict paper.

```{r}
#| label: table1
finaldata <- read.csv(here("data", "mergealldata.csv"), header = TRUE) 
finaldata$OECDf <- factor(finaldata$OECD, levels = c(1,0), 
                          labels = c("Member", "Nonmember"))
finaldata$droughtf <- factor(finaldata$drought, levels = c(1,0), 
                             labels = c("Presence", "Absence"))
finaldata$earthquakef <- factor(finaldata$earthquake, levels = c(1,0), 
                                labels = c("Presence", "Absence"))
finaldata$armconf <- factor(finaldata$armcon, levels = c(1,0), 
                            labels = c("Yes", "No"))

label(finaldata$gdp1000) <- "GDP per capita"
label(finaldata$OECDf) <- "OECD member"
label(finaldata$popdens) <- "Population density"
label(finaldata$urban) <- "Urban residence"
label(finaldata$agedep) <- "Age dependency ratio"
label(finaldata$male_edu) <- "Male education"
label(finaldata$temp) <- "Temperature"
label(finaldata$rainfall1000) <- "Rainfall"
label(finaldata$droughtf) <- "Droughts"
label(finaldata$earthquakef) <- "Earthquakes"

label(finaldata$matmor) <- "Maternal mortality ratio per 100,000 live births"
label(finaldata$infmor) <- "Infant mortality rate per 1,000 live births"
label(finaldata$neomor) <- "Neonatal mortality rate per 1,000 live births"
label(finaldata$un5mor) <- "Under-5 mortality rate per 1,000 live births"

# Set up the rows or labels of the table. Group the two "Yes" and "No" strata
# under a common heading" "Armed conflict exposure".

labels <- list(
  variables = list(matmor = render.varlabel(finaldata$matmor), 
                   un5mor = render.varlabel(finaldata$un5mor),
                   infmor = render.varlabel(finaldata$infmor), 
                   neomor = render.varlabel(finaldata$neomor),
                   gdp1000 = render.varlabel(finaldata$gdp1000),
                   OECDf = render.varlabel(finaldata$OECDf),
                   popdens = render.varlabel(finaldata$popdens),
                   urban = render.varlabel(finaldata$urban),
                   agedep = render.varlabel(finaldata$agedep),
                   male_edu = render.varlabel(finaldata$male_edu),
                   temp = render.varlabel(finaldata$temp),
                   rainfall1000 = render.varlabel(finaldata$rainfall1000),
                   droughtf = render.varlabel(finaldata$droughtf),
                   earthquakef = render.varlabel(finaldata$earthquakef)
                   ), 
  groups=list("", "Armed conflict exposure"))

# Set up the strata or columns of the table.

strata <- c(list(Total=finaldata), split(finaldata, finaldata$armconf))

# Make all values in the table have 1 decimal place.

my_summary <- function(x) {
  # Remove NAs before calculation.
  x <- na.omit(x)
  # Calculate median, 25th and 75th percentiles.
  q <- quantile(x, probs = c(0.25, 0.5, 0.75))
  # Format the output as "median [25th%, 75th%]" with 1 decimal place.
  sprintf("%.1f [%.1f, %.1f]", q[2], q[1], q[3])
}

table1(strata, labels, groupspan=c(1, 2), 
       caption = "Table 1: Description of data used in the study", 
       footnote = "Data given as median [25th percentile, 75th percentile] for continuous variables or counts (%) for categorical variables.",
       render.continuous = my_summary, render.missing = NULL)
```


```{r}
#| label: try-diffmatmor
#| include: false
finaldata %>% 
  select(country_name, ISO, year, matmor) %>% 
  filter(year < 2018) %>% 
  arrange(ISO, year) %>% 
  group_by(ISO) %>% 
  mutate(diffmatmor = matmor - matmor[1L]) 
```
\
Create a figure that shows the trend in maternal mortality for countries that had an increase from 2000 to 2017. First, create a new variable `diffmatmor` that shows the difference between maternal mortality in 2017 and maternal mortality in 2000.

```{r, fig.dim = c(6, 4)}
#| label: figure
#| warning: false
graphdata <- finaldata %>% 
  select(country_name, year, matmor) %>% 
  filter(year == c(2000, 2017)) %>% 
  arrange(country_name, year) %>% 
  group_by(country_name) %>% 
  mutate(diffmatmor = matmor - matmor[1L]) %>%
  filter(diffmatmor > 0)

finaldatag <- finaldata %>% 
  filter(country_name %in% graphdata$country_name)

finaldatag %>%
  ggplot(aes(x = year, y = matmor, group = country_name)) +
  geom_line(aes(color = as.factor(country_name)), alpha = 0.5, lwd = 0.7) +
  xlim(c(2000,2017)) +
  scale_y_continuous(trans='log10') +
  labs(y = "Maternal mortality", x = "Year", color = "Countries")
```
